services:
  db:
    image: postgres:17
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: school_db
      POSTGRES_PASSWORD: Fhntv123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7.0
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - app-network

  bot:
    build: .
    environment:
      DATABASE_URL: postgres://school_db:Fhntv123@db:5432/school_db
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: Web.Web.settings
      BOT_TOKEN: "7433337561:AAH2FAOj2UEebd1zRUEzSKDYwUHHkC9qlJg"
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge