version: '3.8'

services:
  db:
    image: postgres:17
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"



  bot:
    build: .
    command: sh -c "python django_app.py migrate && python -m bot.py
    env_file:
      - ./.env
    restart: always

    depends_on:
      - db
      - redis
    volumes:
      - .:/app
