services:
  db:
    image: postgres:17
    container_name: school-db
    env_file: .env
    environment:
      POSTGRES_SERVER: $POSTGRES_SERVER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - app-network

  redis:
    container_name: school-redis
    image: redis:7.0
    command:
      - redis-server
    env_file: .env
    restart: on-failure
    networks:
      - app-network

  django:
    build: .
    container_name: school-django
    command: >
      sh -c "python django_app.py makemigrations &&
      python django_app.py migrate &&
      python /app/django_app.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: Web.Web.settings
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    container_name: school-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Web/static:/app/Web/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - app-network

  bot:
    build: .
    container_name: school-bot
    command: python bot.py
    environment:
      DJANGO_SETTINGS_MODULE: Web.Web.settings
      BOT_TOKEN: $BOT_TOKEN
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge