# Generated by Django 5.1.1 on 2024-09-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("telegram_id", models.BigIntegerField()),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Username в тг"),
                ),
                (
                    "tg_fullname",
                    models.CharField(max_length=100, verbose_name="Имя в тг"),
                ),
                (
                    "is_access",
                    models.BooleanField(default=True, verbose_name="Доступ к боту"),
                ),
            ],
            options={
                "verbose_name": "Пользователи телеграмм бота",
                "verbose_name_plural": "Пользователи телеграмм бота",
                "db_table": "TgUsers",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "tg_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminPanel.tguser",
                    ),
                ),
            ],
        ),
    ]
