# Generated by Django 5.1.1 on 2024-10-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата отправки"),
                ),
                (
                    "admin_id",
                    models.IntegerField(default=None, verbose_name="ID администратора"),
                ),
                (
                    "message_id",
                    models.IntegerField(verbose_name="ID сообщения в Telegram"),
                ),
                (
                    "lesson_num",
                    models.IntegerField(default=0, verbose_name="Номер класса"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("telegram_id", models.BigIntegerField()),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Username в тг"),
                ),
                (
                    "tg_fullname",
                    models.CharField(max_length=100, verbose_name="Имя в тг"),
                ),
                (
                    "is_access",
                    models.BooleanField(default=True, verbose_name="Доступ к боту"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="Админ?")),
            ],
            options={
                "verbose_name": "Пользователи телеграмм бота",
                "verbose_name_plural": "Пользователи телеграмм бота",
                "db_table": "TgUsers",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame", models.IntegerField(verbose_name="корпус")),
                ("class_num", models.IntegerField(verbose_name="Класс")),
                ("letter", models.CharField(max_length=10, verbose_name="Буква")),
                ("count", models.IntegerField(verbose_name="Количество")),
                ("lesson_num", models.IntegerField(verbose_name="Номер урока")),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminPanel.recorddate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "is_accept",
                    models.BooleanField(default=False, verbose_name="Запись принята"),
                ),
                (
                    "tg_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminPanel.tguser",
                    ),
                ),
            ],
        ),
    ]
