# Generated by Django 5.1.1 on 2024-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Админ?"),
        ),
    ]
