# Generated by Django 5.1.1 on 2024-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Директор?"),
        ),
    ]
