# Generated by Django 5.1.1 on 2024-09-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0002_tguser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_accept",
            field=models.BooleanField(default=False, verbose_name="Запись принята"),
        ),
    ]
