# Generated by Django 5.1.1 on 2024-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0005_remove_user_is_accept_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_accept",
            field=models.BooleanField(default=False, verbose_name="Запись принята"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Директор?"),
        ),
    ]
