# Generated by Django 5.1.1 on 2024-11-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminPanel", "0007_remove_user_is_accept"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Школьный персона",
                "verbose_name_plural": "Школьный персонал",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("director", "Директор"),
                    ("deputy", "Завуч"),
                    ("teacher", "Учитель"),
                ],
                max_length=10,
                null=True,
                verbose_name="Должность",
            ),
        ),
    ]
