# Generated by Django 5.1.1 on 2024-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Record", "0002_latecomerrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="latecomerrecord",
            name="status",
            field=models.CharField(
                choices=[("Без формы", "Без формы"), ("Опоздал", "Опоздал")],
                default="Опоздал",
                max_length=20,
            ),
        ),
    ]
