# Generated by Django 5.1.1 on 2024-11-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Record", "0004_alter_latecomerrecord_status"),
        ("Schooler", "0002_alter_classnum_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LatecomerRecord",
            new_name="IncidentRecord",
        ),
    ]
