# Generated by Django 5.1.1 on 2024-11-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schooler", "0002_alter_classnum_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"verbose_name": "Корпусы", "verbose_name_plural": "Корпусы"},
        ),
        migrations.AlterModelOptions(
            name="classnum",
            options={"verbose_name": "Классы", "verbose_name_plural": "Классы"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Ученики", "verbose_name_plural": "Ученики"},
        ),
        migrations.AlterField(
            model_name="building",
            name="number",
            field=models.IntegerField(verbose_name="Корпус"),
        ),
        migrations.AlterField(
            model_name="classnum",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Schooler.building",
                verbose_name="Корпус",
            ),
        ),
        migrations.AlterField(
            model_name="classnum",
            name="grade",
            field=models.IntegerField(verbose_name="Класс"),
        ),
        migrations.AlterField(
            model_name="classnum",
            name="letter",
            field=models.CharField(max_length=1, verbose_name="Буква"),
        ),
        migrations.AlterField(
            model_name="person",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Schooler.classnum",
                verbose_name="Класс учащегося",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="person",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Отчество"
            ),
        ),
    ]
